[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/coaching"
  to = "/coaching.html"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/signup.html"
  status = 200

[[redirects]]
  from = "/onboarding"
  to = "/onboarding.html"
  status = 200
